# Generated by Django 5.1.1 on 2024-10-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_itemparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка в лалафо'),
        ),
        migrations.AddField(
            model_name='itemparameters',
            name='body_color',
            field=models.CharField(default='', max_length=100, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='itemparameters',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='Обьем двигателя'),
        ),
        migrations.AddField(
            model_name='itemparameters',
            name='instock',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='itemparameters',
            name='model',
            field=models.CharField(default='', max_length=255, verbose_name='модель'),
        ),
        migrations.AddField(
            model_name='itemparameters',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Год выпуска'),
        ),
        migrations.AddField(
            model_name='itemparameters',
            name='transmission',
            field=models.CharField(choices=[('Автомат', 'automatic')], max_length=100, null=True, verbose_name='коробка передач'),
        ),
        migrations.AddField(
            model_name='itemparameters',
            name='wheel_location',
            field=models.CharField(choices=[('Слева', 'left'), ('Справа', 'right'), ('Посередине', 'mid')], max_length=100, null=True, verbose_name='позиция руля'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_mobile',
            field=models.ImageField(upload_to='category/icon_mobile', verbose_name='Иконка для мобилы'),
        ),
        migrations.AlterField(
            model_name='itemparameters',
            name='car_body',
            field=models.CharField(choices=[('Седан', 'sedan'), ('Минивен', 'miniwen')], max_length=255, null=True, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='itemparameters',
            name='condition',
            field=models.CharField(choices=[('Б/У', 'used'), ('Новый', 'new')], max_length=255, null=True, verbose_name='Состояние'),
        ),
    ]
