# Generated by Django 5.1.1 on 2024-10-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_itemimages_options_itemimages_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.CreateModel(
            name='ItemParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('Новый', 'New'), ('Б/У', 'Used')], max_length=50, verbose_name='Состояние')),
                ('car_body', models.CharField(choices=[('Седан', 'Sedan'), ('Хэтчбек', 'Hatchback'), ('Внедорожник', 'SUV')], max_length=255, verbose_name='Кузов')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_parameters', to='cards.category')),
            ],
            options={
                'verbose_name': 'Параметры товара',
                'verbose_name_plural': 'Параметры товаров',
            },
        ),
    ]
