# Generated by Django 5.1.1 on 2024-10-10 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimages',
            options={'ordering': ('order',), 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка в лалафо'),
        ),
        migrations.AddField(
            model_name='itemimages',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_mobile',
            field=models.ImageField(upload_to='category/icon_mobile', verbose_name='Иконка для мобилки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ItemParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег')),
                ('wheel_location', models.CharField(choices=[('Слева', 'left'), ('Справа', 'right'), ('Посередине', 'mid')], max_length=100, null=True, verbose_name='расположение руля')),
                ('body_color', models.CharField(default='', max_length=100, verbose_name='Цвет')),
                ('model', models.CharField(default='', max_length=255, verbose_name='Модель')),
                ('condition', models.CharField(choices=[('Новый', 'new'), ('Б/У', 'used')], max_length=255, null=True, verbose_name='Состояние')),
                ('car_body', models.CharField(choices=[('Седан', 'sedan'), ('Минивен', 'miniwen')], max_length=255, null=True, verbose_name='Кузов')),
                ('year_of_manufacture', models.DateField(null=True, verbose_name='Год выпуска')),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='Обьем двигателся')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='cards.category')),
            ],
        ),
    ]
