# Generated by Django 5.1.1 on 2024-10-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_itemparameters_body_color_itemparameters_car_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="url",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Ссылка в лалафо"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon_mobile",
            field=models.ImageField(
                upload_to="category/icon_mobile", verbose_name="Иконка для мобилки"
            ),
        ),
    ]
